DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   boolean                                 NOT NULL,
    request_id  BIGINT,
    owner       BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);
/*CREATE TABLE IF NOT EXISTS booking
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start  TIMESTAMP WITHOUT TIME ZONE,
    end_booking    TIMESTAMP WITHOUT TIME ZONE,
    item   BIGINT                                  NOT null,
    booker BIGINT,
    status VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);*/


